version: '3'

services:
  webserver:
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:${DIR}
    working_dir: ${WORKING_DIR}
    links:
      - fpm
    command: nginx -g 'daemon off;'
  fpm:
    env_file:
      - .env
    build: ./docker/fpm
    ports:
      - "${FPM_PORT}:9000"
    volumes:
      - .:${DIR}
      - ./docker/fpm/config/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      - ./docker/fpm/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    working_dir: ${WORKING_DIR}
  mysql:
    image: mariadb:${MARIADB_VERSION}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - .:${DIR}
    working_dir: ${WORKING_DIR}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}